apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vfzj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vfzj
    app.kubernetes.io/part-of: tkwch-fix-0075-0029-app
  name: devfile-sample-vfzj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vfzj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vfzj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0029-tenant/tkwch-fix-0075-0029-app/devfile-sample-vfzj@sha256:6068bddb1a2a3f6cdbea4a8d657da453a989a09c9c6fba3f2b14452ac582540b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
